[SourceField] #1230533 - Mass update source field option
Elastic-Suite/gally-standard pull request #69
Opened 2023-11-15 14:20 UTC by PierreGauthier

Todo : 
- Fix front attribut configuration page

2023-11-23 16:00 UTC, botisSmile requested changes

2023-11-27 10:18 UTC, PierreGauthier commented on src/Metadata/Controller/AddSourceFieldOptions.php
> +            $option = $this->serializer->denormalize($optionData, SourceFieldOption::class, 'jsonld', []);
Bien vu, j'ai ajouté cette vérif et un test associé

2023-11-27 10:19 UTC, PierreGauthier commented on src/Metadata/Controller/AddSourceFieldOptions.php
> +    {
L'update est géré, il faut juste spécifier l'id : 
gally/api/packages/gally-standard/src/Metadata/Tests/Api/Rest/SourceFieldTest.php:428

2023-11-27 11:14 UTC, PierreGauthier commented on src/Metadata/Model/SourceField.php
> +    #[Groups(['source_field:read', 'facet_configuration:graphql_read'])]
Corrigé

2023-11-27 12:03 UTC, botisSmile approved these changes

2023-11-27 12:03 UTC, merged