Feat include vector search clause in fulltext query
Elastic-Suite/gally-standard pull request #95
Opened 2024-05-27 09:06 UTC by PierreGauthier

| Q             | A
| ------------- | ---
| Branch?       | master for features / current stable version branch for bug fixes
| Tickets       | #... 
| License       | OSL-3.0

2024-05-29 08:15 UTC, botisSmile requested changes

2024-05-29 08:15 UTC, botisSmile commented on src/Search/Service/ScopableRequestTypeConfiguration.php
> +        $defaultConfig = array_replace_recursive($defaultConfig, $defaultLocalizedConfig, $defaultRequestTypeConfig);
you should  update function description to include this new tree config available.

2024-05-29 15:43 UTC, PierreGauthier commented on src/DependencyInjection/Configuration.php
> -                                                    ->defaultValue('100%')
I remove the default value from configuration in order to prevent that symfony add default value for scope that will prevent our fallback mecanism

2024-05-30 13:34 UTC, botisSmile approved these changes

2024-05-30 13:57 UTC, merged